---
title: "Assignment 04"
authors: "Olivia Gomez and Edward Malcolm"
format:
  html:
    self-contained: true
---

```{r}

library(tidyverse)
library(janitor)
library(ggthemes)
base_url <- "https://www2.census.gov/programs-surveys/demo/datasets/hhp/"
week_url <- "2023/wk52/HPS_Week52_PUF_CSV.zip"

pulse_url <- paste0(base_url, week_url)

dir.create("data")

download.file(
pulse_url,
destfile = "data/pulse52.zip"
)

unzip(zipfile = "data/pulse52.zip", exdir = "data")

pulse <- read_csv("data/pulse2022_puf_52.csv") %>%
  janitor::clean_names()


```

We are using data from the U.S. Census Bureau's Household Pulse Survey - linked [here.](https://www2.census.gov/programs-surveys/demo/datasets/hhp/)

We specifically used data from Week 52.

**Visualization 1**

*Description Here*

```{r}

pulse$income <- factor(pulse$income)

pulse %>%
  filter(income != -99, income != -88) %>%
  ggplot() +
  geom_bar(mapping = aes(x = income), fill = "blue") +
  facet_wrap(~ region, labeller = labeller(region = c(
    `1` = "Northeast",
    `2` = "South",
    `3` = "Midwest",
    `4` = "West"
  ))) +
  scale_x_discrete(labels = c(
    `1` = "<25K",
    `2` = "25K - 34,999K",
    `3` = "35K - 49,999K",
    `4` = "50K - 74,999K",
    `5` = "75K - 99,999K",
    `6` = "100K - 149,999K",
    `7` = "150K - 199,999K",
    `8` = ">200K"
  )) +
   labs(title = "Income Distribution in the Four Regions of the U.S.", y = "Count" , x = "Income Bracket ($)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), plot.title = element_text(hjust = 0.5))
```

**Visualization 2**

*Description here*

```{r}

pulse$region <- factor(pulse$region)

pulse %>%
  group_by(thhld_numper, region) %>%
  mutate(avg_spend = mean(tspndfood, na.rm = TRUE)) %>%
  arrange(region, thhld_numper) %>%
  select(thhld_numper, avg_spend, region) %>%
  ggplot(mapping=aes(x = thhld_numper, y = avg_spend, color = region, group = region)) +
  geom_line() + 
  geom_point() +
  geom_text(aes(label = ""), vjust = -0.5) +
  scale_color_manual(values = c("1" = "red", "2" = "blue", "3" = "green", "4" = "purple"),
                     labels = c("1" = "Northeast", "2" = "South", "3" = "Midwest", "4" = "West")) +
  theme_minimal() +
    labs(title = "Average Amount Spent on Groceries Compared to Household Size, by Region", y = "Average Amount Spent on Groceries ($)", x = "Total Number of People in Household", color = "Region") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))

  
```

**Visualization 3**

*Description Here*

```{r}
pulse %>%
  filter(forclose != -99, forclose != -88) %>%
  ggplot(aes(x = forclose, fill = factor(rrace))) +  
  geom_bar() +
  labs(title = "Foreclosure Likelihood in the Next Two Months, by Race", y = "Count", x = "Response", fill = "Race") +
scale_x_discrete(
    limits = c("1", "2", "3", "4"),
    labels = c(
      "1" = "Very Likely",
      "2" = "Somewhat Likely",
      "3" = "Not Very Likely",
      "4" = "Not at All Likely"
    )) +
  scale_fill_manual(values = c("1" = "red", "2" = "blue", "3" = "green", "4" = "purple"),
                     labels = c("1" = "White", "2" = "Black", "3" = "Asian", "4" = "Any other Race")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), plot.title = element_text(hjust = 0.5))


```

**Graph 4**

educational attainment versus avg number of children in household

```{r}
pulse %>%
  group_by(eeduc) %>%
  summarize(avg_num_child = mean(thhld_numkid, na.rm = TRUE)) %>%
  ggplot(mapping = aes(x = factor(eeduc), y = avg_num_child)) +
  geom_col(fill = "green") +
  geom_text(aes(label = round(avg_num_child, 2)), vjust = -0.5, size = 3) +
  labs(title = "Average Number of Children by Educational Attainment", y = "Average Number of Children" , x = "Education Level") +
  scale_x_discrete(labels = c(
    `1` = "Less than high school",
    `2` = "Some high school",
    `3` = "High school Degree",
    `4` = "Some college",
    `5` = "Associate’s degree",
    `6` = "Bachelor's degree",
    `7` = "Graduate degree"
  )) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), plot.title = element_text(hjust = 0.5))

```
